config/routes.rb
Rails.application.routes.draw do
  resources :cities do 
    resources :shows
  end
  
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  has_many :performances
  has_many :shows, through: :performances
  validates :name, presence: true
  validates :state, presence: true
  validates :country, presence: true

end

app/models/city.rb
class City < ApplicationRecord
  has_many :shows

  validates :name, presence: true
  validates :state, presence: true
  validates :site_name, presence: true, uniqueness: true
end

app/models/performance.rb
class Performance < ApplicationRecord
  belongs_to :band
  belongs_to :show, optional: true
  accepts_nested_attributes_for :band 
end

app/models/show.rb
class Show < ApplicationRecord
  belongs_to :city

  has_many :performances, -> { order(:position) }
  has_many :bands, through: :performances 
  accepts_nested_attributes_for :performances, allow_destroy: true 

  validate  :start_date_validation
  validates :start_datetime, presence: true
  validates :venue, presence: true
  validates :performances, presence: true

  def start_date 
    date = start_datetime.strftime('%m/%d/%Y') if start_datetime
    date unless date == "10/10/1955" #this date is a placeholder which means its blank
  end

  def start_time
    start_datetime.strftime('%H:%M') if start_datetime
  end
 
  def start_time=(t)
    unless t.blank?
      o = start_datetime.nil? ? "10/10/1955" : start_datetime.strftime('%m/%d/%Y')  #if its not nil store original date
      self.start_datetime = DateTime.strptime(o+t,"%m/%d/%Y%H:%M") 
    end
  end

  def start_date=(d)
    unless d.blank?
      o = start_datetime.nil? ? "20:00" : start_datetime.strftime('%H:%M')  #if its not nil store original time 
      self.start_datetime = DateTime.strptime(d+o,"%m/%d/%Y%H:%M") 
    end
  end

  private
   
    def start_date_validation
      if self.start_date.blank? 
        self.errors.add(:start_date, "can't be blank")
      end
    end
    

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def show
    @city = City.find(params[:id])
  end


end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  layout "cities"
  
  def new
    @city = City.find(params[:city_id])
    @show = Show.new(city_id: @city.id)
  end

  def create
    @city = City.find(params[:city_id])
    @show = Show.new(show_params)
    if @show.save
      redirect_to @show.city 
    else
      render 'new'
    end
  end

  def edit
    @city = City.find(params[:city_id])
    @show = Show.find(params[:id])
  end

  def update
    @city = City.find(params[:city_id])
    @show = Show.find(params[:id])
    if @show.update_attributes(show_params)
      remove_missing_performances
      flash[:sucess] = "Show update"
      redirect_to @show.city 
    else
      render 'edit'
    end
  end
  
  private 

  def show_params
    params.require(:show).permit(:start_date, :start_time, :venue, :facebook_event, :city_id, performances_attributes: [:id, :position, :band_id, band_attributes: [:id, :name, :state, :country, :bandcamp]])
  end

  def remove_missing_performances
    curr_performances = @show.performances.map { |p| p.attributes}
    param_performances  = show_params[:performances_attributes].map{|param| param["id"].to_i}
    missing = curr_performances.reject do |curr| 
       param_performances.include?(curr["id"]) 
    end
    missing.each {|miss| @show.performances.destroy(miss["id"]) }
  
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/date_format_helper.rb
module DateFormatHelper

  def print_time(t) 
    if t.min == 00
      t.strftime("%l%P")
    else
      t.strftime("%l:%M%P")
    end
  end


end

app/helpers/shows_helper.rb
module ShowsHelper
  def time_options
    i = 0
    times = Array.new
    for n in 1..24 
      sub = n > 12 ? 12 : 0
      period = sub == 0 ? 'am' : 'pm'
      times[i] = ["#{n-sub}:00 #{period}","#{n}:00"]
      i = i + 1
      times[i] = ["#{n-sub}:30 #{period}","#{n}:30"]
      i = i + 1  
    end
    times
  end

  def country_display(band_fields)
    if(!band_fields.object.international)
      "hide"      
    end 
  end

  def state_display(band_fields)
    if(band_fields.object.international)
      "hide"
    end 
  end

  def format_bands_form_params(performances)
    performances.map do |p|
      b = p.band
      state =  (b.country == "USA" || b.country == "") ? b.state : b.country
      {name: b.name, perf_id: p.id, id: b.id, state: state, bandcamp: b.bandcamp, soundcloud: nil}
    end
  end


  def state_options
    states = 
    [
    ['Alabama', 'AL'],
    ['Alaska', 'AK'],
    ['Arizona', 'AZ'],
    ['Arkansas', 'AR'],
    ['California', 'CA'],
    ['Colorado', 'CO'],
    ['Connecticut', 'CT'],
    ['Delaware', 'DE'],
    ['District of Columbia', 'DC'],
    ['Florida', 'FL'],
    ['Georgia', 'GA'],
    ['Hawaii', 'HI'],
    ['Idaho', 'ID'],
    ['Illinois', 'IL'],
    ['Indiana', 'IN'],
    ['Iowa', 'IA'],
    ['Kansas', 'KS'],
    ['Kentucky', 'KY'],
    ['Louisiana', 'LA'],
    ['Maine', 'ME'],
    ['Maryland', 'MD'],
    ['Massachusetts', 'MA'],
    ['Michigan', 'MI'],
    ['Minnesota', 'MN'],
    ['Mississippi', 'MS'],
    ['Missouri', 'MO'],
    ['Montana', 'MT'],
    ['Nebraska', 'NE'],
    ['Nevada', 'NV'],
    ['New Hampshire', 'NH'],
    ['New Jersey', 'NJ'],
    ['New Mexico', 'NM'],
    ['New York', 'NY'],
    ['North Carolina', 'NC'],
    ['North Dakota', 'ND'],
    ['Ohio', 'OH'],
    ['Oklahoma', 'OK'],
    ['Oregon', 'OR'],
    ['Pennsylvania', 'PA'],
    ['Puerto Rico', 'PR'],
    ['Rhode Island', 'RI'],
    ['South Carolina', 'SC'],
    ['South Dakota', 'SD'],
    ['Tennessee', 'TN'],
    ['Texas', 'TX'],
    ['Utah', 'UT'],
    ['Vermont', 'VT'],
    ['Virginia', 'VA'],
    ['Washington', 'WA'],
    ['West Virginia', 'WV'],
    ['Wisconsin', 'WI'],
    ['Wyoming', 'WY']
  ]
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/cities/show.html.erb
<% @city.shows.each do | show | %>
  <p><%= show.start_datetime.strftime("%A, %b %d") %></p>
  <p> 
  <% show.bands.each do |band| %>
    <a target="_blank" href="https://<%= band.bandcamp %>.bandcamp.com"><%= band.name %></a> 
    <%  unless show.bands.last == band %> // <% end %> 
      
  <% end %>
  -<%= print_time show.start_datetime  %> @ <%= show.venue  %>
  </p>
 

<% end %>
<br />
<br />
<br />
<br />
<p><%= link_to "List a show", new_city_show_path(@city)  %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Shows</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= content_for?(:sub_template) ? yield(:sub_template) :  yield %>
    </div>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <%= stylesheet_pack_tag 'application' %>
  </body>
</html>

app/views/layouts/cities.html.erb
<% content_for :sub_template do %>
  <div class="page-header">
    <h1><%= @city.site_name  %></h1>
    <p><%= @city.tag_line %></p>
  </div>
  <%= yield %>
<% end %>
<%= render template: "layouts/application" %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
     <div id="error_explanation">
       <div class="alert alert-danger">
         The form contains <%= pluralize(model.errors.count, "error") %>.
       </div>
     </div>
<% end %>

app/views/shows/_bands_form.html.erb
<%= show_form.fields_for :performances do |performance_form| %>
    <%= performance_form.fields_for :band do |band_form| %>
      <%= band_form.label :name, class: "sr-only" %>
      <%= band_form.text_field :name, class: "form-control", placeholder: 'name' %>
      <%= band_form.label :state, class: "sr-only" %>
      <%= band_form.text_field :state, class: "form-control", placeholder: 'state' %>
    <% end %>
  <% end %>

app/views/shows/_show_form.html.erb
<%= form_for [@city, @show], html: {class: "form-horizontal"} do |f| %>
  <%= render 'shared/error_messages' , model:  @show  %>
  <%= f.hidden_field :city_id %>

  <div id="show-fields">
    <div class="form-group">
      <%= f.label :start_date, class: "sr-only" %>
      <%= f.text_field :start_date, class: "form-control", placeholder: 'When', id: "datepicker" %>
      <small class="input-error"><%= @show.errors.full_messages_for(:start_date).first %></small>
    </div>
    <div class="form-group">
      <%= f.label :start_time, class: "sr-only" %>
      <%= f.select :start_time, time_options, {selected: "19:00"},{class: "form-control start-time"} %>
    </div>
    <div class="form-group">
      <%= f.label :venue, class: "sr-only" %>
      <%= f.text_field :venue, class:"form-control", placeholder: 'Venue' %>
      <small class="input-error"><%= @show.errors.full_messages_for(:venue).first %></small>
    </div>
    <div class="form-group">
      <%= f.label :facebook_event, class: "sr-only" %>
      <%= f.text_field :facebook_event, class:"form-control", placeholder: 'Facebook event' %>
    </div>
  </div>
  <hr class="mb-4">
  <div id="show-fields">
    <%= react_component("BandsForm", { displayError: !@show.errors[:performances].empty?, data: format_bands_form_params(@show.performances)}) %>
  </div>
  <hr class="mb-4">
  <div class="form-group">
    <%= f.submit 'Submit', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/shows/edit.html.erb
<% console %>
<h4 class="mb-3">Edit a show</h4>
  <%= render "show_form" %>

app/views/shows/new.html.erb
<h4 class="mb-3">List a show</h4>
  <%= render "show_form" %>

app/views/static_pages/home.html.erb
<h1>diyshws</h1>
<p>Finally.</p>